In [1]:
# Attention Örnek Kodu
import numpy as np

# Basit bir girdi dizisi simüle edelim (örneğin, 3 kelimelik bir cümle, her kelime 4 boyutlu bir vektörle temsil ediliyor)
# Girdi Matrisi (Şekil: dizi uzunluğu, embedding boyutu)
# Kelime 1, Kelime 2, Kelime 3
input_sequence = np.array([
    [1.0, 0.5, 0.1, 0.8], # Kelime 1 vektörü
    [0.2, 0.7, 0.9, 0.3], # Kelime 2 vektörü (belki "önemli" bir kelime)
    [0.6, 0.4, 0.7, 0.5]  # Kelime 3 vektörü
])

print("Girdi Dizisi (Simüle Edilmiş Kelime Vektörleri):")
print(input_sequence)
print("-" * 30)

# Senaryo 1: Attention Mekanizması Yok (Basit Ortalama veya Sabit Ağırlıklandırma)
# Bu senaryoda, her kelime çıktıya eşit veya sabit bir ağırlıkla katkıda bulunur.
# En basit haliyle ortalama alma.

output_no_attention = np.mean(input_sequence, axis=0)

print("Attention Olmayan Çıktı (Basit Ortalama):")
print(output_no_attention)
print("Açıklama: Her kelime çıktıya eşit derecede katkıda bulundu.")
print("-" * 30)


# Senaryo 2: Attention Mekanizması Var (Basit Bir Dikkat Simülasyonu)
# Attention, hangi girdi öğelerinin çıktı için daha önemli olduğuna karar verir
# ve onlara daha yüksek ağırlıklar atar.
# Bu ağırlıklar, model tarafından öğrenilir ve hangi kelimenin (pozisyonun)
# çıktı için ne kadar önemli olduğunu gösterir. Toplamları 1'e eşittir.
# Örneğin, 2. kelimenin daha önemli olduğunu varsayalım (indeks 1).
attention_weights = np.array([0.2, 0.6, 0.2]) # Kelime 1, Kelime 2, Kelime 3 için ağırlıklar

# Dikkat ağırlıklarını girdi dizisine uygulayalım (ağırlıklı toplam)
# Her kelime vektörünü kendi dikkat ağırlığı ile çarpıp topluyoruz.
output_with_attention = np.sum(input_sequence * attention_weights[:, np.newaxis], axis=0)

print("Attention İle Çıktı (Ağırlıklı Toplam):")
print(output_with_attention)
print(f"Kullanılan Dikkat Ağırlıkları: {attention_weights}")
print("Açıklama: Çıktı, dikkat ağırlıklarına göre kelimelerin ağırlıklı toplamıdır.")
print("Daha yüksek ağırlığa sahip kelimeler (burada Kelime 2) çıktı üzerinde daha fazla etkiye sahiptir.")
print("-" * 30)

# Karşılaştırma
print("Karşılaştırma:")
print("Attention Olmayan Çıktı:", output_no_attention)
print("Attention İle Çıktı:   ", output_with_attention)
print("\nFarklılıklar, attention'ın girdi vektörlerini önemlerine göre yeniden ağırlıklandırmasından kaynaklanır.")

Girdi Dizisi (Simüle Edilmiş Kelime Vektörleri):
[[1.  0.5 0.1 0.8]
 [0.2 0.7 0.9 0.3]
 [0.6 0.4 0.7 0.5]]
------------------------------
Attention Olmayan Çıktı (Basit Ortalama):
[0.6        0.53333333 0.56666667 0.53333333]
Açıklama: Her kelime çıktıya eşit derecede katkıda bulundu.
------------------------------
Attention İle Çıktı (Ağırlıklı Toplam):
[0.44 0.6  0.7  0.44]
Kullanılan Dikkat Ağırlıkları: [0.2 0.6 0.2]
Açıklama: Çıktı, dikkat ağırlıklarına göre kelimelerin ağırlıklı toplamıdır.
Daha yüksek ağırlığa sahip kelimeler (burada Kelime 2) çıktı üzerinde daha fazla etkiye sahiptir.
------------------------------
Karşılaştırma:
Attention Olmayan Çıktı: [0.6        0.53333333 0.56666667 0.53333333]
Attention İle Çıktı:    [0.44 0.6  0.7  0.44]

Farklılıklar, attention'ın girdi vektörlerini önemlerine göre yeniden ağırlıklandırmasından kaynaklanır.


In [4]:
# df_reviews DataFrame'ini kullanıyoruz (veri yükleme adımından)
# Eğer bu hücreyi tek başına çalıştırıyorsanız, df_reviews'ı tekrar yüklemeniz gerekebilir.

if 'df_reviews' in locals() and not df_reviews.empty:
    # 'Metin' sütununu bilgi kaynağı olarak alalım
    knowledge_source = df_reviews['Metin'].tolist()

    print(f"Bilgi Kaynağına Eklenen Yorum Sayısı: {len(knowledge_source)}")
    print("\nBilgi Kaynağından İlk 5 Yorum:")
    for i, review in enumerate(knowledge_source[:5]):
        print(f"{i+1}. {review}")

else:
    print("df_reviews DataFrame'i bulunamadı veya boş. Lütfen veri yükleme adımını çalıştırın.")

df_reviews DataFrame'i bulunamadı veya boş. Lütfen veri yükleme adımını çalıştırın.
